### ISSUE TITLE
browserlist in package.json produces error when starting

### ISSUE THREAD

**Issue by SebastianOpriel** [International-Data-Spaces-Association/ids-metadata-broker-open-frontend#2]
Hi, 
I received an error, running the searchfrontend locally. The bug is pretty well described and fixed at following stackoverflow thread: 
https://stackoverflow.com/questions/67552020/how-to-fix-error-failed-to-compile-node-modules-react-leaflet-core-esm-pat

To avoid such issues you may commit `package-lock.json` too.

**Comment by waleedshabbir1** [comment]
Fixed with #7

**Comment by NehaThawani44** [comment]
@SebastianOpriel @waleedshabbir1  the package-lock has been committed hence closing this issue

**Comment by SebastianOpriel** [comment]
Thanks! Now it works with the package-lock. 

I figured out how to reproduce my issue: 
Running `npm update --legacy-peer-deps` and `npm adit fix` and finally `npm run start` leads to the error linked in my initial comment.
