### ISSUE TITLE
Make Broker Open Frontend use Broker Open Core

### ISSUE THREAD

**Issue by SebastianOpriel** [International-Data-Spaces-Association/ids-metadata-broker-open-frontend#6]
I have assumed, that the open frontend would make use of the latest open core broker. Unfortunately it seems, that the close source version of the broker is used: https://github.com/International-Data-Spaces-Association/ids-metadata-broker-open-frontend/blob/3e7bc7ecbd138054dc8abed8eced1243c0cd3d07/docker/composefiles/frontend-dev/docker-compose.yml#L11

It would be great, if you could provide an example, how the open frontend could work with the latest open core broker (`registry.gitlab.cc-asp.fraunhofer.de:4567/eis-ids/broker-open/core:latest`)

**Comment by sebbader** [comment]
`registry.gitlab.cc-asp.fraunhofer.de:4567/eis-ids/broker-open/core:latest` is also outdated, the current docker image should be `registry.gitlab.cc-asp.fraunhofer.de/eis-ids/broker-open/core:latest`

**Comment by SebastianOpriel** [comment]
@sebbader This trivial issue is open for around one month. Could you tell me when this will be fixed?

**Comment by NehaThawani44** [comment]
@SebastianOpriel The port is updated in all the docker-compose files as of now, also the latest image should be pulled and should have a 5.0.0-SNAPSHOT version.
