### ISSUE TITLE
Provide package-lock.json

### ISSUE THREAD

**Issue by SebastianOpriel** [International-Data-Spaces-Association/ids-metadata-broker-open-frontend#8]
I encounter an error while installing npm packages. Please provide your package-lock.json, as it is a best practice to be committed to GIT (see e.g. https://stackoverflow.com/a/44210813)

**Comment by SebastianOpriel** [comment]
After some debugging: I disagree with @waleedshabbir1 regarding the PR https://github.com/International-Data-Spaces-Association/ids-metadata-broker-open-frontend/pull/7. It did not solve the problem addressed here: https://github.com/International-Data-Spaces-Association/ids-metadata-broker-open-frontend/issues/2. Additionally I needed to use the command `npm install --legacy-peer-deps`

**Comment by waleedshabbir1** [comment]
Package-lock.json is now locked in 
https://github.com/International-Data-Spaces-Association/ids-metadata-broker-open-frontend/commit/be6beb6a939f7381feac7742a0bbae49909f39b3

**Comment by NehaThawani44** [comment]
This duplicate issue, package-lock is committed.
